### ISSUE TITLE
bad mobile render on ff and chromium

### ISSUE THREAD

**Issue by 532910** [AnySoftKeyboard/AnySoftKeyboard.github.io#11]
https://anysoftkeyboard.github.io/about/

![image](https://user-images.githubusercontent.com/14617699/61107372-6cd64500-a488-11e9-9e8b-dbe6a86dce67.png)

**Comment by AnXh3L0** [comment]
Thanks for opening an issue for this, it will be fixed today.

**Comment by AnXh3L0** [comment]
Fixed on commit 01f8aa327f6facd1fedbe34f78996e5ba32f6de1.

**Comment by 532910** [comment]
It's better now, but the license still has a horizontal scroll. 
![image](https://user-images.githubusercontent.com/14617699/61155539-de021080-a4f9-11e9-93fe-314ce050c750.png)
