### ISSUE TITLE
PayPal Link Needs To Be Updated

### ISSUE THREAD

**Issue by ankushdas9** [AnySoftKeyboard/AnySoftKeyboard.github.io#13]
I was trying to donate via PayPal - but it won't let me. It just keeps on asking me to sign in again and verify it. Even though my PayPal works fine for others. Maybe use the Paypal.me link instead of the old URL?

**Comment by ankushdas9** [comment]
@menny just a heads up for anyone who's working on the website!

**Comment by AnXh3L0** [comment]
Thanks for opening this issue @ankushdas9. I'll ask Menny for a new link and update the website.

**Comment by menny** [comment]
@AnXh3L0, please use GitHub Sponsors (https://github.com/sponsors/menny) and PayPal (https://www.paypal.me/menny)

**Comment by AnXh3L0** [comment]
@menny please re-add me in the ASK org so I can push the changes to the repo.

**Comment by menny** [comment]
@AnXh3L0 done. Can you also take a look at the security warning at https://github.com/AnySoftKeyboard/AnySoftKeyboard.github.io/network/alerts

**Comment by AnXh3L0** [comment]
@menny Still don't have access to those settings in this repo.

**Comment by menny** [comment]
Did you accept the invite? There should be an email from GitHub

**Comment by AnXh3L0** [comment]
No email from GitHub yet.

**Comment by menny** [comment]
Also, do you have an idea for an avatar for https://github.com/orgs/AnySoftKeyboard/teams/developers ?
I want to use its avatar for https://github.com/orgs/AnySoftKeyboard/teams/web

**Comment by menny** [comment]
@AnXh3L0 , I don't see any issue on the setting side. Can you try to create a PR and push that?

**Comment by AnXh3L0** [comment]
I believe the network alert was probably related to outdated bundle dependencies, this last commit should probably fix it.

**Comment by AnXh3L0** [comment]
About the avatar, you can contact me on Telegram/Signal/WhatsApp or something else so I can send you the images.
