### ISSUE TITLE
Update social links to include Mastodon

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard.github.io#20]
- [ ] Official mastodon account: https://hachyderm.io/@anysoftkeyboard.
- [ ] Remove all Google Plus references
- [ ] Keep twitter? Or remove it?

**Comment by menny** [comment]
@AnXh3L0 can you take a look at this?

**Comment by menny** [comment]
@AnXh3L0 I think I added Mastodon correctly. Can you check?

**Comment by AnXh3L0** [comment]
Hi @menny, yes, you added it correctly.
